version: '3.8'

services:
  unturned-server:
    # Uncomment next two lines if building the image locally:
    #build: .
    #image: unturned-server:latest
    # Uncomment next line if using the prebuilt image from GitHub:
    image: ghcr.io/TheQuib/unturned-server
    container_name: unturned-server
    networks:
      - unturned

networks:
  unturned:
    driver: bridge